### PR TITLE
Add missing react dependency

### PR DESCRIPTION
**Pull request by Snailedlt**
pnpm dev failed due to the missing "react" dependency. This fixes that issue.

### CODE REVIEW

**Comment by jacobsfletch** [comment]
@Snailedlt hmm you shouldn't need to list react here because it is installed as a Payload dependency. Can you pass the `--legacy-peer-deps` flag?

**Comment by Snailedlt** [comment]
Possibly, I'll try next time I get the chance

**Comment by Snailedlt** [comment]
@jacobsfletch I got the same "missing dependency" error for this ecommerce example: https://github.com/payloadcms/payload/tree/master/templates/ecommerce

When running with the `--legacy-peer-deps` the issue was solved, re-running without `--legacy-peer-deps` also worked. I assume the same will be true for this example.

So to summarize the fix is to either:
1. Install react first, then run the dev script 
  i. `pnpm install react`
  ii. `pnpm dev`
2. Run the dev script with the `--legacy-peer-deps` option
  i. `pnpm dev --legacy-peer-deps`

**Comment by jacobsfletch** [comment]
Hey @Snailedlt, looks like you've found a temporary workaround. This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/ecommerce. I'm going to close this PR out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).

**Pull request closed without merging**
